ProductMVC/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProductMVC.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

ProductMVC/Models/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProductMVC.Models
{
    public class Company
    {
        public int Id { get; set; }
        public string PersianName { get; set; }
        public string EnglishName { get; set; }
        public int? CountryId { get; set; }
        public virtual Country Country { get; set; }
    }
}

ProductMVC/Models/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProductMVC.Models
{
    public class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

ProductMVC/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProductMVC.Models
{
    public class Product
    {
        public int Id { get; set; }
        [Required]
        [Display(Name ="دسته بندی")]
        public int? CategoryId { get; set; }
        public virtual Category Category { get; set; }
        [Required]
        [Display(Name = "کمپانی")]
        public int CompanyId { get; set; }
        public virtual Company Company { get; set; }
        [Required]
        [Display(Name = "نام محصول")]
        public string ModelName { get; set; }
        [Display(Name = "توضیحات")]
        public string Description { get; set; }
    }
}

ProductMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProductMVC/Controllers/ProductController.cs
using ProductMVC.DAL;
using ProductMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductMVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductMVCDBContext db;

        public ProductController()
        {
            db = new ProductMVCDBContext();
        }

        public ActionResult Index()
        {
            var list = new List<Product>();
            list = db.Products.ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var Categories = db.Categories.ToList();
            var selectlist = new SelectList(Categories, "Id", "Name");
            ViewBag.Categories = selectlist;

            var Companies = db.Companies.ToList();
            var selectlist1 = new SelectList(Companies, "Id", "PersianName");
            ViewBag.Companies = selectlist1;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product Entity)
        {
            if (!ModelState.IsValid)
            {

            }

            if (db.Products.Any(x => x.Id == Entity.Id))
            {
                ViewBag.Message = "این کالا ثبت شده است.";
                return View(Entity);
            }

            db.Products.Add(Entity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var Entity = db.Products.Find(Id);

            if (Entity == null)
            {
                ViewBag.Message = "محصول مورد نظر یافت نشد.";
                return RedirectToAction("Index");
            }

            var Categories = db.Categories.ToList();
            var selectlist = new SelectList(Categories, "Id", "Name");
            ViewBag.Categories = selectlist;

            var Companies = db.Companies.ToList();
            var selectlist1 = new SelectList(Companies, "Id", "PersianName");
            ViewBag.Companies = selectlist1;

            return View(Entity);
        }

        [HttpPost]
        public ActionResult Edit(Product Entity)
        {
            var Categories = db.Categories.ToList();
            var selectlist = new SelectList(Categories, "Id", "Name");
            ViewBag.Categories = selectlist;

            var Companies = db.Companies.ToList();
            var selectlist1 = new SelectList(Companies, "Id", "PersianName");
            ViewBag.Companies = selectlist1;

            db.Entry(Entity).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int code)
        {
            var Entity = db.Products.FirstOrDefault(x => x.Id == code);

            if (Entity == null)
            {
                ViewBag.Message = "یافت نشد.";
                return RedirectToAction("Index");
            }

            db.Products.Remove(Entity);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

ProductMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<br />
@Html.ActionLink("لیست محصولات","Index","Product",new { name = ""},new { @class = "btn btn-info"})

ProductMVC/Views/Product/Create.cshtml
@model ProductMVC.Models.Product
@{
    /**/

    ViewBag.Title = "افزودن محصول";
}

<h2>افزودن محصول</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.DisplayNameFor(x => x.CategoryId)
        @Html.DropDownListFor(x => x.CategoryId, (SelectList)ViewBag.Categories, "نوع محصول را انتخاب کنید...", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
    </div>
    <br />
    <div class="form-group">
        @Html.DisplayNameFor(x => x.CompanyId)
        @Html.DropDownListFor(x => x.CompanyId, (SelectList)ViewBag.Companies, "کمپانی مورد نظر را انتخاب کنید...", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CompanyId)
    </div>
    <br />
    <div class="form-group">
        @Html.DisplayNameFor(x => x.ModelName)
        @Html.TextBoxFor(x => x.ModelName, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ModelName)
    </div>
    <br />
    <div class="form-group">
        @Html.DisplayNameFor(x => x.Description)
        @Html.TextBoxFor(x => x.Description, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Description)
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="ذخیره" class="btn btn-success" />
    </div>


}

ProductMVC/Views/Product/Edit.cshtml
@model ProductMVC.Models.Product
@{
    ViewBag.Title = "ویرایش";
}

<h2>اصلاح محصول</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.DisplayNameFor(x => x.CategoryId)
        @Html.DropDownListFor(x => x.CategoryId, (SelectList)ViewBag.Categories, "نوع محصول را انتخاب کنید...", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
    </div>
    <br />
    <div class="form-group">
        @Html.DisplayNameFor(x => x.CompanyId)
        @Html.DropDownListFor(x => x.CompanyId, (SelectList)ViewBag.Companies, "کمپانی مورد نظر را انتخاب کنید...", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CompanyId)
    </div>
    <br />
    <div class="form-group">
        @Html.DisplayNameFor(x => x.ModelName)
        @Html.TextBoxFor(x => x.ModelName, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ModelName)
    </div>
    <br />
    <div class="form-group">
        @Html.DisplayNameFor(x => x.Description)
        @Html.TextBoxFor(x => x.Description, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Description)
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="ذخیره" class="btn btn-success" />
    </div>
}

ProductMVC/Views/Product/Index.cshtml
@model List<ProductMVC.Models.Product>
@{
    ViewBag.Title = "فهرست";
}

<h2>لیست محصولات</h2>

<table class="table">

    <tr>
        <th style="text-align:center;">
            @Html.DisplayNameFor(x => x.FirstOrDefault().CategoryId)
        </th>
        <th style="text-align:center;">
            @Html.DisplayNameFor(x => x.FirstOrDefault().CompanyId)
        </th>

        <th style="text-align:center;">
            @Html.DisplayNameFor(x => x.FirstOrDefault().ModelName)
        </th>
        <th style="text-align:center;">
            @Html.DisplayNameFor(x => x.FirstOrDefault().Description)
        </th>
        <th style="text-align:center;">
            @Html.ActionLink("افزودن محصول", "Create", "Product", new { name = "" }, new { @class = "btn btn-primary" })

        </th>

    </tr>
    @foreach (var item in Model)
    {
        <tr class="@item.Id">

            <td style="text-align:center;">
                @item.Category.Name
            </td>

            <td style="text-align:center;">

                @item.Company.PersianName
            </td>



            <td style="text-align:center;">
                @item.ModelName
            </td>

            <td style="text-align:center;">
                @item.Description
            </td>

            <td style="text-align:center;">
                @Html.ActionLink("ویرایش", "Edit", new { Id = item.Id }, new { @class = "btn btn-warning" })

                @Html.ActionLink("حذف", "Delete", new { code = item.Id }, new { onclick = "return confirm('آیا از حذف این محصول مطمئن هستید؟');", @class = "btn btn-danger" })

            </td>

        </tr>
    }
</table>

ProductMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -  خانه</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body style="direction:rtl; font-family:'Calibri">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="direction:rtl; float:right;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("خانه", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AppleFamily</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>